### ISSUE TITLE
EOFException in ping

### ISSUE THREAD

**Issue by made-by-traxam** [made-by-traxam/minecraft-server-status#10]
Pinging `play.hivemc.com` results in an error although the server is online.

Used command: `mc-status play.hivemc.com`

```
11:57:34.616 ForkJoinPool.commonPool-worker-3              ServerPinger    ERROR  Error while pinging Minecraft server
java.io.EOFException: null
	at java.base/java.io.DataInputStream.readByte(DataInputStream.java:271)
	at br.com.azalim.mcserverping.MCPingUtil.readVarInt(MCPingUtil.java:71)
	at br.com.azalim.mcserverping.MCPing.getPing(MCPing.java:127)
	at am.trax.discord.minecraft.ping.ServerPinger.ping(ServerPinger.java:28)
	at am.trax.discord.minecraft.command.StatusCommand.lambda$execute$0(StatusCommand.java:34)
	at com.jagrosh.jdautilities.command.CommandEvent.lambda$reply$1(CommandEvent.java:237)
	at net.dv8tion.jda.api.requests.Request.lambda$onSuccess$0(Request.java:95)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1429)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

**Comment by made-by-traxam** [comment]
Seems like other tools are troubled with this server too, for example [https://mcsrvstat.us/server/play.hivemc.com](https://mcsrvstat.us/server/play.hivemc.com)

**Comment by lucaazalim** [comment]
I have the same problem while using https://github.com/lucaazalim/minecraft-server-ping and trying to ping `play.hivemc.com`. I'm not sure how to fix it yet. Please let me know if you realize what the issue is.
